### ISSUE TITLE
段落間に空行がなく読みにくい

### ISSUE THREAD

**Issue by harupong** [progit-ja/progit#1]
http://twitter.com/akabekobeko/status/369602003522965504

**Comment by m-takagi** [comment]
たぶん、epub/ProGit.css あたりをいじって対応することになるんでしょうねえ。

p {
    text-indent: 1em;      /\* 段落冒頭の字下げ _/
    margin-top: 0.5em;     /_ 段落開始前の余白 _/
    margin-bottom: 0.5em;  /_ 段落終了後の余白 */
}

とか。

**Comment by harupong** [comment]
ありがとうございます。公開中の MOBI ファイルで試したのですが、
- Kindle for iOS -> 空行あり
- Sumatra PDF(Windows) の MOBI ビューアー -> 空行なし

とちぐはぐでした。後者のビューアーが特殊な仕様なのか、margin をどう変えても空行が入らず。このあたり難しいですね...

環境を変えてもう少し試してみるつもりですが、状況が変わらないようなら既知の不具合ってことでサイトに注記いれておしまいにするかもしれません。

**Comment by akabekobeko** [comment]
Twitter のほうにも返信しましたが、本件の現象は Mac 標準のプレビューで PDF 版を表示したときに発生するようです。以下にスクリーンショットを貼っておきます。

![ss-01](https://f.cloud.github.com/assets/1257526/993111/855678e0-0991-11e3-974b-a30cad969b03.png)

**Comment by harupong** [comment]
@akabekobeko 
状況のご報告ありがとうございます。PDF は出版物を意図して作成されているため、段落間に空行が入らないようになっています。EPUB版、MOBI版には空行が入っていますので、必要に応じてそちらをご利用ください。(Twitter でもお返事しましたが、記録としてこちらにも記しておきます。)
