### ISSUE TITLE
v2対応

### ISSUE THREAD

**Issue by m-takagi** [progit-ja/progit#11]
というわけで、v2が公開されたようですね。
- https://medium.com/@chacon/living-the-future-of-technical-writing-2f368bd0a272
- https://github.com/progit/progit2
- http://git-scm.com/book/en/v2

翻訳的な観点でのv1からの変更点は、
- フォーマットがMarkdownからAsciidocに変わった
- 各国語の翻訳用に、それぞれ[別のリポジトリ](https://progit.org/translations)を用意するようになった

というわけで、これまでよりも、いろんな人に協力してもらいやすそうになった気がします。あと、その気になれば、画像も日本語化できるようになったというわけですね。

流れとしては、
1. progit/progit2 をフォークして日本語訳を進めてみる（最初のほうは、ほぼv1と同じだとのこと）
2. 「ここまでやったから、jaのリポジトリを作ってくれ！」と、progit/progit2-ja のメンテナに立候補する
3. あとはみんなでボチボチ進めていく

みたいな感じになるのだと思います。さて、どなたか「私がv2日本語版のメンテナを引き受けましょう！」という人はいらっしゃるでしょうか。

**Comment by harupong** [comment]
ここ数週間Chaconさんが progit/progit のissueをせっせと片付けていたので「そろそろかな？」と思っていましたが、["soft-launched"](https://twitter.com/chacon/status/525793066503135234)されましたね。発売日はTBDだそうなので、そこに向けて修正も複数入っていきそうです。

v2日本語版のメンテナですが、私で差し支えなければやってみたいです。作業の方は挙げていただいた案で進めてみます。重複作業が発生するのは避けたい（ないような気もしますが）ので、露・韓にならって「日本語訳始めてます」issueを progit/progit2 にたてておこうと思います。

**Comment by harupong** [comment]
@m-takagi 以下の2点、ご意見いただけますでしょうか。
1. 原文を訳出原稿に埋め込むべきか
   
   progit/progit の更新作業時、更新された原文に対応する訳文を探すのにとても苦労しました。v2では、原文を埋め込むことでそれを避けたいなぁと思っています。更新対象が原文・訳文の2つになる、というデメリットは大きいですが、
   - 対応する訳文を探す
   - 既訳原文と更新原文のdiff
   
   が簡単になるというメリットはやはり捨てがたいです。
2. 底リビジョン（底本相当）を定めるべきか（章ごとでもOK）

**Comment by m-takagi** [comment]
メンテナ、助かります。フル稼働できるか怪しいですが、私もできるだけお手伝いするつもりでいます。

> 原文を訳出原稿に埋め込むべきか

はい、これはv1でミスったところのひとつです。翻訳を読んでて「？？？」となったときに、原文にすぐアクセスできたほうがツッコミを入れやすいんですよね。ぜひ残しておきましょう。AsciiDocならコメントアウトもしやすそうなので、

http://www.methods.co.nz/asciidoc/userguide.html#X26

このコメントアウトなら、うまくすれば原文の更新をそのままmergeできるかも。

> 底リビジョン（底本相当）を定めるべきか（章ごとでもOK）

とりあえず最新を追いかけるのはいいとして、今の翻訳がどのリビジョンをベースにしているかはわかったほうがいいですね。ファイルの先頭に、底リビジョンのハッシュをコメントとしてつけておくとかですかねえ。

**Comment by harupong** [comment]
一緒に作業できて光栄です。どうぞよろしくお願いします。

原文埋め込みの件、ありがとうございます。ではその方向で進めます。

> このコメントアウトなら、うまくすれば原文の更新をそのままmergeできるかも。

プログラマーの皆さんからのhackが楽しみです :smile: 他の翻訳プロジェクト https://github.com/jekyllrb-ja/ で「ローカルファイルのコメントアウトした内容とGitHub上の原文とのdiffツール」というのを使っているので、うまく流用できれば、と思っています。

> ファイルの先頭に、底リビジョンのハッシュをコメントとしてつけておく

ファイルに直接持たせると諸々の自動化が楽になりそうですが、翻訳者の作業が煩雑にならないかちょっと心配しています。上述のプロジェクトでは
- 自動化のために、ファイルの先頭に底リビジョンのハッシュをコメントとしてつける
- GitHubのissueとmilestoneを使って底リビジョンごとの進捗管理をしている

の2つをやっていて、メンテナ・翻訳者ともに作業の煩雑感が否めません。

当分は原文の更新も頻繁でしょうし、いずれは上記のいずれかで管理するつもりでいつつ、まずは何もせずにスタートしようと思っています…

**Comment by m-takagi** [comment]
> 当分は原文の更新も頻繁でしょうし、いずれは上記のいずれかで管理するつもりでいつつ、まずは何もせずにスタートしようと思っています…

はい、それでいいと思います。

やりやすいように進めていくのがいちばんです :)

**Comment by harupong** [comment]
ありがとうございます。作業手順は試行錯誤中ですが、ひとまず1章を訳してみました。

https://github.com/harupong/progit2/tree/ch01/book/01-introduction

AsciidocのレンダリングはAsciidoctor.js Live Previewで確認しています。

https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia

大半は既訳からのコピペ作業ですが、
1. installing.asc（ほぼ全面リライト）
2. command-line.asc（追加された節）

の2節は新たに訳した部分です。ご確認いただければ幸いです。progit/progit2-ja リポジトリを作ってもらえたようなので、今日中には一度プッシュしてみようと思います。

**Comment by m-takagi** [comment]
あ、セクションごとにファイルを分けるようになったんですね。
これは翻訳する側にはありがたいですねえ。

> 1. installing.asc（ほぼ全面リライト）

一箇所だけ、原文の消し忘れがありました。

> If you don't have it installed already, it will prompt you to install it.

あと、この文の「it」が指すのは、Git単体じゃなくて、(Gitも含めた)Xcode Command Line Toolsなのかなあ、と思いました。

# ターミナルで「git」と打つ
# →「それを使いたければXcode Command Line Toolsを入れないと。どうする？」
# →Xcode Command Line Toolsのインストールに進む
# みたいな流れ。

それ以外は、特に問題はないかと思います。細かいところは、progit/progit2-ja が動き出してから、issueとかで進めましょう。

**Comment by harupong** [comment]
ご確認ありがとうございます。修正しておきました。OSXのターミナルは随分と賢いんですねぇ。

progit/progit2-ja のwrite accessがもらえていないようなので、しばし待ち状態です。

**Comment by harupong** [comment]
write access がついたので早速プッシュしてみました。

http://git-scm.com/book/ja/v2

直すべきところは多そうですが、ひとまず開通！！ということでクローズします。引き続きよろしくお願いします。
