### ISSUE TITLE
MOBI 版の目次が巻末に来ている

### ISSUE THREAD

**Issue by harupong** [progit-ja/progit#2]
> Kindle Touch,
> Kindle Paperwhite，
> Kindle Fire HD 7
> Kindle Fire HD 8.9
> において基本動作は確認できました．
> 
> 問題なのは目次の方で，通常の意味での目次が，
> あるにはあるんですが，一番最後に来てます．
> 通常のKindle書籍なら，目次があるのは「使い始める」の前，表紙の直後だと思います．
> 
> GoToから選択するポップアップメニューの方の目次もありますが，
> あまりに長すぎてPaperWhite やTouchではスクロールするのが不可能なレベルです．
> また，なぜかFireHD 8.9ではまともに表示できませんでした．
> またポップアップ目次には，一番最後のページにある通常の目次自体の項目が含まれていません．
> 
> これだと多くの人は「目次がない」と思ってしまいますし，
> また「目次のある場所にジャンプするための目次をスクロールするのが大変」という
> 問題に直面することになります。  
> (via email)
### 参考
- [宮川さんPodcast ep6、KDP での本の作り方 - naoyaのはてなダイアリー](http://d.hatena.ne.jp/naoya/20130321/1363838408)

**Comment by yabuki** [comment]
http://progit-ja.github.io/ に示してある mobi ファイルをダウンロードして、Nexus 10のkindle appへ送って読み始めたのですが、目次がみつかりません。この issue を参考にして最後のページへ行きましたが、目次ではありません。また検索で「目次」を検索しても見つかりませんでした。

これは意図していない挙動に思えますが、もしかして? 意図通りですか? 内容自体には今のところ気がついた部分はありません。翻訳に関しては感謝しております。

**Comment by harupong** [comment]
レポートありがとうございます。iOSのkindleアプリでも再現しました。

#5 の対応の副作用かも、と思いつつ、MOBI版の目次は色々とやっかいで「あっちを立てればこっちが立たず」状態です。

調査してみますので少しお時間ください。

**Comment by harupong** [comment]
電子書籍には TOC が2種類ある。
- Content TOC: いわゆる「目次」。紙の書籍のように、本ごとに任意の形式で作れる。手動で作る必要がある。
- Metadata TOC: 電子書籍リーダーで「目次」ボタンを押したときに表示される目次。ツールが自動生成する。

MOBI フォーマットは Metadata TOC の扱いに難があり(巻末に Content TOC を挿入することで擬似的に Metadata TOC を持つ。)、calibre が生成する MOBI データもその制約を受ける。calibre のオプションで目次を巻頭に挿入することはできるが[非推奨](http://manual.calibre-ebook.com/cli/ebook-convert.html#cmdoption-ebook-convert-azw3-output--mobi-toc-at-start)である。

詳しくは [calibre のFAQ](http://manual.calibre-ebook.com/faq.html#what-s-the-deal-with-table-of-contents-in-mobi-files) を参照のこと。

よって、#2 は 「MOBI フォーマットの仕様」なのでクローズする。

@yabuki

目次、元に戻ったと思いますのでご確認いただければ幸いです。また、#5 の対策として AZW フォーマットのファイルを追加しました。Kindle だとそちらの方がいい具合に表示されると思います。ぜひお試しください。

**Comment by yabuki** [comment]
@harupong 対応ありがとうございます。

まずは、mobiの方で、巻末に目次が見えたことを報告さしあげます。

azw3ファイルについては、send to kindle が認識しないので、メールで kindle appにつっこんでも音沙汰がないので、様子見ですけども、これは私がわかってないためだと思うので、ちょっと
調べてまいります。ではでは

**Comment by yabuki** [comment]
@harupong kindle のカスタマ・サポートに連絡したら、azw3 のファイルを send-to-kindle で持っていくことはできないという回答をもらいました。

が、よく考えたら、Calibre で、送信すれば良かったことに思い至りました。手元で読めるようになりました。

**Comment by harupong** [comment]
わざわざサポートに確認していただいたんですね。お手間をかけてしまい、申し訳ありませんでした :bow: Kindle Paperwhite ではUSBケーブルでPCと接続してファイル転送ができたので、簡単な事かと思っておりました…

とにかく、うまく表示されたようでよかったです。ご確認ありがとうございました！

**Comment by harupong** [comment]
目次を冒頭に持ってくることが calibre で[非推奨](http://manual.calibre-ebook.com/cli/ebook-convert.html#cmdoption-ebook-convert-azw3-output--mobi-toc-at-start)であるため、対応しません。
