### ISSUE TITLE
pdf版で ~/.gitconfig が欠けている

### ISSUE THREAD

**Issue by yoichi** [progit-ja/progit#4]
Pro Git 日本語版 PDFの1.5で"~ file:"とファイル名が欠けています。
epub版では”~/.gitconfig file:”とソース通りに表示されています。

**Comment by harupong** [comment]
Issueありがとうございます！

調べてみたところ、MarkdownファイルのLatex変換に使ってるpandocのバグのようです 
jgm/pandoc/issues/964 。開発者の言うように1.11.1以降では修正されていることが確認できました。

現在、本家リポジトリに投げてるPRがいくつかあるので、それらが取り込まれたらこのバグが解消してるPDFをリリースしたいと思います。

**Comment by harupong** [comment]
@yoichi 修正版をサイトにアップしました～
