### ISSUE TITLE
MOBI版の目次が折りたためない

### ISSUE THREAD

**Issue by southly** [progit-ja/progit#5]
Kindle Paperwhite Previewer にて NCX 表示を確認すると
すべての項目がフラットになっています。これではちょっと不便です。
これが ebook-convert のバグなのか仕様なのかは調べていません。
ただ、EPUB 版を kindlegen で変換するときちんと章の構造を反映した目次が出来上がります。

**Comment by harupong** [comment]
こちらも Issue 登録ありがとうございます！

> Kindle Paperwhite Previewer にて NCX 表示を確認するとすべての項目がフラットになっています。
> Kindle Paperwhite(2013) でも同様の問題を確認できました。これは不便ですね...ロシア語等、多言語で更新されている MOBI 版も同様の問題があるようです。
> 
> ただ、EPUB 版を kindlegen で変換するときちんと章の構造を反映した目次が出来上がります。
> 色々と試していただいたようで感謝多謝です。こちらでも kindlegen を使い、章の構造を反映した目次を持つ MOBI 版を、EPUB 版から変換できました。

Quick Fix として、ひとまず日本語版は kindlegen で変換したものに差し替えておこうと思います。とはいえ、ファイルサイズが ebook-convert で生成したものと比べ2倍以上とあまり嬉しくない状態なので、併せて本家の方に Issue として報告しておきます。

**Comment by southly** [comment]
ありがとうございます。
ファイルサイズの件はいい解決策が出てくることを願っています。

**Comment by harupong** [comment]
:blush:

**Comment by harupong** [comment]
@southly 

[同じようなバグレポート](https://bugs.launchpad.net/calibre/+bug/1176678?utm_content=buffere1127)が calibre のバグトラッカーにあり、calibre の中の人 @kovidgoyal さんが 「MOBI じゃなくて AZW 使ってね」とのコメント :grin: 

progit/progit の方で用意されてるスクリプトで AZW フォーマットを生成したところ、章の構成を反映した目次を Kindle Paperwhite(2013) で表示させることが出来ました。

[Pro Git 日本語版サイト](http://progit-ja.github.io/)の方にファイルをアップしておきましたので、ご確認いただければ幸いです。
