### ISSUE TITLE
公開鍵をメールでやりとりすることの問題点

### ISSUE THREAD

**Issue by harupong** [progit-ja/progit#7]
<blockquote class="twitter-tweet" lang="en"><p>Git Pro日本語訳4章でGitサーバに公開鍵を配備する過程で「(訳注: メールなんかで送っていいの? とツッコミたいところだ……)」ってあるけど公開鍵なんだから何が問題やねんとこっちがツッコミたいという感想しかない。何か見落としてるかな</p>&mdash; 410 Gone (@chuyaso) <a href="https://twitter.com/chuyaso/statuses/427130545399529473">January 25, 2014</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by harupong** [comment]
悪意を持った第三者によって通信データが傍受され**「公開鍵を他人のものに差し替えられてしまう」**リスクがあるので、公開鍵を
- メールの添付ファイルでやりとりするのよくない
- 広く Web 上に公開するのよくない(ただし公開をHTTPSに限れば良し？)

というのがツッコミの背景？

**Comment by harupong** [comment]
あと、全てをメールでやりとりする場合は、**「接続先アドレス」が正しいサーバーかどうかの保証がない** という指摘もある。SSH だし安心～、と思って繋いだサーバーが、実は悪意を持った第三者が立てたものだった、という。

**Comment by harupong** [comment]
@m-takagi #662 についてどのようにお考えですか？

**Comment by m-takagi** [comment]
公開鍵を第三者に見られること自体は何の問題もないけど、その公開鍵がほんとうに本人のものなのかを確かめる手段がないのは問題です。

参考： http://www.ipa.go.jp/security/pki/031.html

…というのが訳注の意図でした。

言葉足らずなところもあるし本論とは関係のない話題でもあるので、 progit/progit#662 については、あれはあれでよいのではないかと思います。

本来なら原文に手を入れるべきところを訳注に逃げてしまったのが敗因ですね :)

**Comment by rinopo** [comment]
#662 については、こちらの議論を見ないまま投稿してしまいました。
大変失礼しました。
また、ご説明いただきありがとうございました。
あらためて @m-takagi さんのご指摘のほうが正当のように思います。
別途、issue を立てましょうか。

**Comment by m-takagi** [comment]
いや、そんなお気になさらず :)

指摘していただいたおかげで、元の訳注が言葉足らずだったことがわかったわけです。

かといって詳しく補足してしまうと本文より注釈のほうが長くなってしまいそうですし、今のまま（訳注を消したまま）でかまわないと（私は）思います。

**Comment by harupong** [comment]
@m-takagi 回答ありがとうございます。正確な補足は訳注ではなく「訳者あとがき」くらいのスペースが必要でしょうし、私も訳注は消したままで良いと思います(個人的には、本文の文体と訳注の口調の大きな違いが気になっていました)。

@rinopo コメントありがとうございます。本文に関するプルリクエストは、今後もどしどし本家の方へ送ってくださいまし :) 私の方で疑問があれば、メンテナーがマージする前になんらかアクション起こしますので(今回は間に合いませんでした。すみません)。

この issue は一端クローズしておきます。お二方ありがとうございました。

**Comment by rinopo** [comment]
ありがとうございました！
